// <auto-generated />
namespace Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class initial_11042015 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_11042015));
        
        string IMigrationMetadata.Id
        {
            get { return "201504111956034_initial_11042015"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
